export const PORTFOLIO_CONFIG = {
  appName: 'JayShell',
  version: '0.23.0',
  hostName: 'jayshell',
  ownerName: 'Jayasurya Pazhani',
  siteUrl: 'https://jay-shell.vercel.app/',
  repositoryUrl:
    'https://github.com/jayasuryapazhani/jay-shell',
  contactEmail: 'pazhanijayasurya@gmail.com',
  linkedInUrl:
    'https://www.linkedin.com/in/jayasurya-pazhani/',
  githubUrl: 'https://github.com/jayasuryapazhani',
  resumeUrl: '/Jayasurya-Pazhani-Resume.pdf',
  homeDirectory: '/home/jayasurya',
} as const

export const AVAILABLE_COMMANDS = [
  'help',
  'info',
  'ls',
  'cd',
  'pwd',
  'whoami',
  'about',
  'skills',
  'experience',
  'education',
  'projects',
  'contact',
  'socials',
  'resume',
  'stack',
  'features',
  'testing',
  'architecture',
  'lessons',
  'github',
  'demo',
  'store',
  'history',
  'reset',
  'reboot',
  'clear',
  'cls',
] as const